feat: improvements to track 01 and added checks

diff --git a/01-terraform-set-up/check-container b/01-terraform-set-up/check-container
--- a/01-terraform-set-up/check-container
+++ b/01-terraform-set-up/check-container
@@ -1,4 +1,14 @@
 #!/bin/bash
 set -euxo pipefail
 
+if ! terraform init; then
+     fail-message "Terraform init failed, please check your providers file and try again"
+     exit 1
+fi
 
+if ! terraform plan; then
+     fail-message "Terraform plan failed, please check your credentials and try again"
+     exit 1
+fi
+
+exit 0
